# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(499, 762)
        MainWindow.setStyleSheet("background-color:black;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(-20, 0, 531, 231))
        self.frame.setStyleSheet("background-color:#FF6347;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(90, 60, 381, 111))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color:white;")
        self.label.setObjectName("label")
        self.input_amount = QtWidgets.QLineEdit(self.centralwidget)
        self.input_amount.setGeometry(QtCore.QRect(50, 370, 400, 61))
        self.input_amount.setStyleSheet("border: 2px solid #FF6347;\n"
"border-radius: 30;\n"
"color:white;\n"
"font-size: 26px;\n"
"")
        self.input_amount.setAlignment(QtCore.Qt.AlignCenter)
        self.input_amount.setObjectName("input_amount")
        self.output_amount = QtWidgets.QLineEdit(self.centralwidget)
        self.output_amount.setGeometry(QtCore.QRect(50, 563, 400, 61))
        self.output_amount.setStyleSheet("border: 2px solid #FF6347;\n"
"border-radius: 30;\n"
"color:white;\n"
"font-size: 26px;\n"
"")
        self.output_amount.setAlignment(QtCore.Qt.AlignCenter)
        self.output_amount.setObjectName("output_amount")
        self.output_currency = QtWidgets.QComboBox(self.centralwidget)
        self.output_currency.setGeometry(QtCore.QRect(50, 463, 400, 61))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.output_currency.setFont(font)
        self.output_currency.setStyleSheet("border: 2px solid #FF6347;\n"
"border-radius: 30;\n"
"color:white;\n"
"\n"
"")
        self.output_currency.setObjectName("output_currency")
        self.output_currency.addItem("USD")
        self.output_currency.addItem("CNY")
        self.output_currency.addItem("CHF")
        self.output_currency.addItem("EUR")
        self.output_currency.addItem("GBP")
        self.output_currency.addItem("AUD")
        self.output_currency.addItem("JPY")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(50, 660, 400, 51))
        self.pushButton.setObjectName("pushButton")
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton {\n"
"    background-color:#FF6347;\n"
"    color:white;\n"
"    border-radius:25;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color:#FF4500;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.input_currency = QtWidgets.QLabel(self.centralwidget)
        self.input_currency.setGeometry(QtCore.QRect(50, 270, 400, 61))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.input_currency.setFont(font)
        self.input_currency.setStyleSheet("border: 2px solid #FF6347;\n"
"border-radius: 30;\n"
"color:white;\n"
"")
        self.input_currency.setAlignment(QtCore.Qt.AlignCenter)
        self.input_currency.setObjectName("input_currency")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "КОНВЕРТЕР ВАЛЮТ"))
        self.output_currency.setItemText(0, _translate("MainWindow", "USD"))
        self.output_currency.setItemText(1, _translate("MainWindow", "CNY"))
        self.output_currency.setItemText(2, _translate("MainWindow", "CHF"))
        self.output_currency.setItemText(3, _translate("MainWindow", "EUR"))
        self.output_currency.setItemText(4, _translate("MainWindow", "GBP"))
        self.output_currency.setItemText(5, _translate("MainWindow", "AUD"))
        self.output_currency.setItemText(6, _translate("MainWindow", "JPY"))
        self.pushButton.setText(_translate("MainWindow", "КОНВЕРТИРУЙ"))
        self.input_currency.setText(_translate("MainWindow", "RUB"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
